# Generated by Django 5.0.6 on 2024-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
